### ISSUE TITLE
LoginError: Error=BadAuthentication and Unhandled rejection Error

### ISSUE THREAD

**Issue by imKota** [dweinstein/node-google-play-cli#6] opened 2017-06-29 00:52 UTC
![screen 2017-06-29 03-51-13](https://user-images.githubusercontent.com/24241471/27666701-5a449f62-5c7e-11e7-9de6-a8bdcfcac12b.png)

**Comment by dweinstein** [comment] 2017-07-02 14:45
dupe of https://github.com/dweinstein/node-google-play-cli/issues/5

**Closed as completed by dweinstein** 2017-07-02 14:45 UTC
